image: docker



services:
	- docker:dind

before_scripts:
	- export
	- docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} registry.gitlab.com
	
build:
	script:
		- docker build -t registry.gitlab.com/nikdvy/skillbox:${CI_COMIT_SHORT_SHA} -t registry  .
		- docker build . -t skillbox:${CI_COMIT_SHORT_SHA}
